name: marine-heatwaves
channels:
  - mamba
  - defaults
dependencies:
  - python
  - ipykernel
  - s3fs
  - xarray
  - numpy
  - pandas
  - lxml
  - html5lib
  - beautifulsoup4
  - scikit-image
  - scipy
  - matplotlib
  - cartopy
  - netcdf4
  - zarr
  - ocetrac
