name: marine-heatwaves
channels:
  - mamba
  - defaults
dependencies:
  - python
  - ipykernel
  - s3fs
  - xarray
  - numpy
  - pandas
  - matplotlib
  - bokeh
  - datashader
  - holoviews
  - netcdf4
  - zarr
  - ocetrac
